version: 2

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      # Install poetry
      - pip install poetry
      # Install dependencies
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with dev
