name: PyPIRelease

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install Poetry
      uses: abatilo/actions-poetry@v3
      with:
        poetry-version: latest

    - name: Install Poetry Dependencies
      shell: bash
      run: poetry install --with dev

    - name: Build the Wheel
      shell: bash
      run: rm -rf dist && poetry build

    - name: Deploy on PyPi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.REALPYPIPW }}
        repository-url: https://upload.pypi.org/legacy/
