name: PyPIRelease

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install Pip Dependencies
      shell: bash
      run: pip install build wheel

    - name: Build the Wheel
      shell: bash
      run: rm -rf dist/ build/ && python3 -m build

    - name: Deploy on PyPi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.REALPYPIPW }}
        repository-url: https://upload.pypi.org/legacy/
